CREATE TABLE PUBLISHER(
PUB_NAME VARCHAR2(20) PRIMARY KEY,
PUB_ADDRESS VARCHAR2(20),
PUB_PHONE NUMBER(10)); 
drop table publisher;
INSERT INTO PUBLISHER VALUES('Pearson','Bangalore',98234555);
INSERT INTO PUBLISHER VALUES('Tatamc','Bangalore',98234545);
INSERT INTO PUBLISHER VALUES('Laxmi','Bangalore',99234545);
INSERT INTO PUBLISHER VALUES('Roopao','India', 593291930);
INSERT INTO PUBLISHER VALUES('Aavishkar','India',98565789);
SELECT * FROM publisher;  


CREATE TABLE BOOK (
BOOKID int PRIMARY KEY, 
TITLE VARCHAR2(10), 
PUB_NAME references publisher on delete cascade,
PUB_YEAR int)
 PARTITION BY RANGE( YEAR )
 (PARTITION p1 VALUES LESS THAN(2001),
 PARTITION p2 VALUES LESS THAN(2005),
 PARTITION P3 VALUES LESS THAN (2010),
 PARTITION P4 VALUES LESS THAN(MAXVALUE));
 
 select * from v$option where parameter = 'Partitioning';
 
 